### ISSUE TITLE
private的问题

### ISSUE THREAD

**Issue by imyyq-star** [2tu/fit#17]
`@SharedPreferenceAble
public class User
{
    private int age;
    private String name;
    private boolean isMan;

    public int getAge()
    {
        return age;
    }

    public void setAge(int age)
    {
        this.age = age;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public boolean isMan()
    {
        return isMan;
    }

    public void setMan(boolean man)
    {
        isMan = man;
    }
}
`

以上是我的JavaBean，可是保存不了，必须把属性的private去掉才可以。但是去掉就破坏了封装。
请问有办法解决吗？

**Comment by 2tu** [comment]
目前没有支持private，可以通过修改FitProcessor.java实现

**Comment by imyyq-star** [comment]
请问有没有计划什么时候实现呢？

**Comment by 2tu** [comment]
有了，正在研究，由于android中没有Introspector，应该会使用反射获取对应getter/setter

**Comment by 2tu** [comment]
请升级至0.3.0使用

**Comment by imyyq-star** [comment]
编译错误：Unable to parse @SharedPreferenceAble shared.请问是怎么回事？

**Comment by imyyq-star** [comment]
另外有个疑问，Fit的clear和get和save，都需要Context。而SharedPreference的Context可以是Application，那么为何不让使用者做一个初始化动作 Fit.init(Application Context);，然后Fit的方法就都可以不用Context了。

**Comment by 2tu** [comment]
把你的bean文件贴出来看一下
Fit不用长期持有Context

**Comment by imyyq-star** [comment]
我明白了，原来被@SharedPreferenceAble注解的类，一定要有默认的无参构造器
